import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.scss";
import { LayoutChildren } from "@/types/cardtype";
import { Provider } from "@/provider";

const inter = Inter({ subsets: ["latin"] });
const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<LayoutChildren>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${dmSans.className} bg-black text-white max-w-[1440px] mx-auto`}>
        <Provider>{children}</Provider>

      </body>
    </html>
  );
}
